/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BotDS;

import org.junit.jupiter.api.Test;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        //Library classUnderTest = new Library();
    }
}
