/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DSBot;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import javax.security.auth.login.LoginException;

import com.jagrosh.jdautilities.commons.waiter.EventWaiter;

import DSBot.commands.CommandExecutor;
import DSBot.Library;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.requests.GatewayIntent;
import net.dv8tion.jda.api.utils.ChunkingFilter;
import net.dv8tion.jda.api.utils.MemberCachePolicy;

public class Library {
	
	private final EventWaiter eventWaiter = new EventWaiter();
	
    public static void main(String ... args) throws Exception {
    	//new Library().start(System.getenv().get("TOKEN"));
    	new Library().start("OTczNTU2MDIyNDkwODU3NDg0.GhDgCO.-VYwkcRplebo_V0dB-3NTAVclNoGkZDy-CzhYk");
    }
    
    public void start(String token) throws LoginException, InterruptedException, IOException, ClassNotFoundException {
    	JDABuilder
		.createDefault(token)
		.setChunkingFilter(ChunkingFilter.ALL) // enable member chunking for all guilds
		.setMemberCachePolicy(MemberCachePolicy.ALL)
		.enableIntents(GatewayIntent.GUILD_MEMBERS)
        .addEventListeners(new CommandExecutor(this), eventWaiter)
        .build()
        .awaitReady()
        .getGuilds()
        .parallelStream()
        .filter(g -> !new File(g.getName()).exists())
        .forEach(g -> {
			try { Files.createDirectory(Paths.get(g.getName() + "/")); }
			catch (IOException e) { e.printStackTrace(); }
		});
    }
    
    public static void copyDirectory(String sourceDirectoryLocation, String destinationDirectoryLocation) 
    		  throws IOException {
    		    Files.walk(Paths.get(sourceDirectoryLocation))
    		      .forEach(source -> {
    		          Path destination = Paths.get(destinationDirectoryLocation, source.toString()
    		            .substring(sourceDirectoryLocation.length()));
    		          try {
    		              Files.copy(source, destination);
    		          } catch (IOException e) {
    		              e.printStackTrace();
    		          }
    		      });
    		}
    
    public EventWaiter getEventWaiter() { return eventWaiter; }
}
