/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DSBot;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

import javax.security.auth.login.LoginException;

import com.jagrosh.jdautilities.commons.waiter.EventWaiter;

import DSBot.commands.CommandExecutor;
import net.dv8tion.jda.api.JDABuilder;
import net.dv8tion.jda.api.requests.GatewayIntent;
import net.dv8tion.jda.api.utils.ChunkingFilter;
import net.dv8tion.jda.api.utils.MemberCachePolicy;

public class Library {
	
	private final EventWaiter eventWaiter = new EventWaiter();
	
    public static void main(String ... args) throws Exception {
    	//new Library().start(System.getenv().get("TOKEN"));
    	new Library().start("OTczNTU2MDIyNDkwODU3NDg0.G9qJBm.E0TzN3zdjVC4AL9unQoos5Z8e1rebsro23AET0");
    }
    
    public void start(String token) throws LoginException, InterruptedException, IOException, ClassNotFoundException {
    	JDABuilder
		.createDefault(token)
		.setChunkingFilter(ChunkingFilter.ALL) // enable member chunking for all guilds
		.setMemberCachePolicy(MemberCachePolicy.ALL)
		.enableIntents(GatewayIntent.GUILD_MEMBERS)
        .addEventListeners(new CommandExecutor(this), eventWaiter)
        .build()
        .awaitReady()
        .getGuilds()
        .parallelStream()
        .filter(g -> !new File(g.getName()).exists())
        .forEach(g -> {
			try { Files.createDirectory(Paths.get(g.getName() + "/")); }
			catch (IOException e) { e.printStackTrace(); }
		});
    }
    
    public EventWaiter getEventWaiter() { return eventWaiter; }
}
